type RegisteredUser {
  ukey: ID
  confirm_token: ID
}
type AccessToken {
  ukey: ID
  access_token: ID
}
type Profile {
  ukey: ID
  email: String
  cities: String
}
type Query {
  profile(ukey: String!): Profile
  validate(ukey: String!): Boolean
}
type Mutation {
  register(
    email: String!
    password: String!
    confirmation: String!
  ): RegisteredUser
  login(email: String!, password: String!): AccessToken
  confirm(ukey: String!): Boolean
  refresh: AccessToken
  saveCities(cities: String!, ukey: String!): Boolean
}
